### ISSUE TITLE
LocARNA output cuts the sequence position if the header is to long

### ISSUE THREAD

**Issue by teresa-m** [s-will/LocARNA#45]
Hello Sebastian,

today I noticed that if the sequence position of the header are 4 digits the displayed header in the output is missing the last two digits of the header. 

One example call is:
/some/dir/locarna-1.9.1/bin/mlocarna --tgtdir /some/dir/ --max-diff-am '30' --indel -350 --indel-opening -500 --struct-weight 190 --tau 0 -min-prob '0.005' --write-structure --pw-aligner-options "--pos-output" ../BRALIBASE/k2/U6/U6.apsi-80.sci-86.no-1.raw.fa -moreverbose -v 

which produced this line in the output:
Perform progressive alignment ...
Align input/U58510_1_7471_75 + input/Z17282.1_96-198 --> intermediates/intermediate1

However the BRALIBASE fasta file looks like this:

BRALIBASEk2/k2/U6/U6.apsi-80.sci-86.no-1.raw.fa:
>U58510.1_7471-7569
gcguucacgcaucuuuaaaauuggaacgauacagagaagauuagcauggccccugcgcaaggaugacacgcauaauccgagauuagguuccuuuauuua
>Z17282.1_96-198
gucccuucggggacauccgauaaaauuggaacgauacagagaagauuagcauggccccugcgcaaggaugacacgcacaaaucgagaaaugguccaaauuuuu

Thanks for your support and greetings,
Teresa

**Comment by s-will** [comment]
In this case, mlocarna intentionally uses shortened filenames
(generally, filenames are derived from the fasta names but are not
necessarily identical, e.g. due to shortening and replacing certain
filename incompatible symbols). The tool mlocarna_nnames could be used
to reproduce this name-mangling (e.g. useful, if you really need to
access the files from a script).
Anyway, the full fasta names are reported in the output files again.

Cheers, Sebastian
