### ISSUE TITLE
locarnate: Invalid CODE attribute

### ISSUE THREAD

**Issue by tao-bioinfo** [s-will/LocARNA#47]
After successfully installation, the command `locarna` is OK, but the command `locarnate` fails:
```
[zhut@cotton locarna-1.9.2.1]$ locarnate
Invalid CODE attribute: prototype($) at /usr/local/bin/../lib/perl/MLocarna/Aux.pm line 89.
BEGIN failed--compilation aborted at /usr/local/bin/../lib/perl/MLocarna/Aux.pm line 89.
Compilation failed in require at /usr/local/bin/../lib/perl/MLocarna/MatchProbs.pm line    @@@19.
BEGIN failed--compilation aborted at /usr/local/bin/../lib/perl/MLocarna/MatchProbs.pm line 19.
Compilation failed in require at /usr/local/bin/../lib/perl/MLocarna.pm line 12.
BEGIN failed--compilation aborted at /usr/local/bin/../lib/perl/MLocarna.pm line 12.
Compilation failed in require at /usr/local/bin/locarnate line 96.
BEGIN failed--compilation aborted at /usr/local/bin/locarnate line 96. # #

**Comment by s-will** [comment]
Thanks, @billzt, for reporting. In principle, this is a known issue with old versions of perl (<= 5.18),
which affects most of the perl scripts in LocARNA (locarnate, mlocarna,...)
Since 5.18 is very old, it should pay off to update.
This issue should have been fixed in 1.9.2.1, but unfortunately my changes were incomplete. I am currently building the bug fix release 1.9.2.2.

**Comment by s-will** [comment]
@billzt, could you please close the issue if this resolves your problem; otherwise let me know

**Comment by tao-bioinfo** [comment]
Yes, now it is OK
