### ISSUE TITLE
2.0.0-RC8 fails: No rule to make target 'exparna_p.1'

### ISSUE THREAD

**Issue by yurivict** [s-will/LocARNA#63]
```
gmake[2]: Entering directory '/usr/ports/biology/locarna/work/LocARNA-2.0.0RC8/Doc'
Making all in man
gmake[3]: Entering directory '/usr/ports/biology/locarna/work/LocARNA-2.0.0RC8/Doc/man'
gmake[3]: *** No rule to make target 'exparna_p.1', needed by 'all-am'.  Stop.
gmake[3]: Leaving directory '/usr/ports/biology/locarna/work/LocARNA-2.0.0RC8/Doc/man'
gmake[2]: *** [Makefile:399: all-recursive] Error 1
gmake[2]: Leaving directory '/usr/ports/biology/locarna/work/LocARNA-2.0.0RC8/Doc'
gmake[1]: *** [Makefile:667: all-recursive] Error 1
```

FreeBSD 12 amd64

**Comment by s-will** [comment]
Hey @yurivict, thanks for reporting the issue so promptly.
Since I don't have a BSD system to reproduce the issue, I need a little help: Is this compiled using the release tar file (at https://github.com/s-will/LocARNA/releases/download/v2.0.0RC8/locarna-2.0.0RC8.tar.gz) or cloning the repository (e.g. using the release tag)? (The release tar.gz already includes the man pages, such that the behavior would be even more puzzling.)

**Comment by yurivict** [comment]
It is compiled using the tarball that you mentioned.

> The release tar.gz already includes the man pages, such that the behavior would be even more puzzling.

Makefiles attempt to build thee man page and fail to find the source. Makefile might still be building it even when it is already present if the rules say so.

**Comment by s-will** [comment]
Hey again,
I trried to reproduce your problems under FreeBSD 12 (starting from the official VM image for VirtualBox).
Finally, I got working binaries, so this is not a general LocARNA-BSD incompatibility. For me this didn't work out of the box (e.g. required to rerun autotools), so your problems may be due to some specific detail in the installation ...
Could you explain in more details, what you did to compile locarna 2.0.0RC8 from the tar.gz

**Comment by s-will** [comment]
ping @yurivict -- more details would be highly appreciated, otherwise I would have to assume, since I cannot reproduce your compilation problems, that this is not a locarna-specific issue?!
