### ISSUE TITLE
'make check' fails at locarnate 'Calculate multiple alignment...'

### ISSUE THREAD

**Issue by RaumZeit** [s-will/LocARNA#68]
Running `make check` with the recent 1.9.2.3 release fails with the following error when testing for proper function of `locarnate`:

```
============================================================
TEST locarnate
CALL locarnate ./../../Data/Examples/archaea.fa

Calculate pair probabilities... done!
Calculate pairwise alignment with locarna 21/21 (Seq 6 <-> Seq 7)... done!      
Parse pairwise alignments... done!
Calculate multiple alignment...
t_coffee  -in=Ltest_results/input.lib -outfile=test_results/mult/tcoffee.aln 1>test_results/mult/tcoffee.out 2>test_results/mult/tcoffee.err
Calculate multiple alignment... done!
diff: test_results/mult/tcoffee.aln: No such file or directory
==================== DIFFERENT
```
I have t-coffee installed and all other checks seem fine

**Comment by s-will** [comment]
Thanks for reporting the issue.
Just for a first quick response, the good news: if you don't use locarnate, don't worry ;)
However, maybe the test fails due to an incompatibility with newer versions of t_coffee. I quickly tested successfully with
version 12.0 (i.e. not the very newest one). Which version of T-Coffee do you use?

t_coffee -version
PROGRAM: T-COFFEE Version_12.00.7fb08c2 (2018-12-11 09:27:12 - Revision 7fb08c2 - Build 211)
